import { ReservationStatus } from '../domain/entities/Reservation';

export interface CreateReservationDTO {
  userId: string;
  menuId: string;
  menuVariationId: string;
  reservationDate: Date;
  isAutoGenerated?: boolean;
}

export interface UpdateReservationDTO {
  menuVariationId?: string;
  status?: ReservationStatus;
}

export interface ReservationResponseDTO {
  id: string;
  userId: string;
  menuId: string;
  menuVariationId: string;
  reservationDate: Date;
  status: ReservationStatus;
  isAutoGenerated: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}
