export enum ReservationStatus {
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
}

export interface ReservationUpdateData {
  menuVariationId?: string
  status?: ReservationStatus
}

export class Reservation {
  constructor(
    public readonly id: string,
    public readonly userId: string,
    public readonly menuId: string,
    public menuVariationId: string,
    public readonly reservationDate: Date,
    public status: ReservationStatus,
    public readonly isAutoGenerated: boolean,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date
  ) {}

  public cancel(): void {
    this.status = ReservationStatus.CANCELLED
  }

  public activate(): void {
    this.status = ReservationStatus.ACTIVE
  }

  public update(data: ReservationUpdateData): void {
    if (data.menuVariationId !== undefined)
      this.menuVariationId = data.menuVariationId
    if (data.status !== undefined) this.status = data.status
  }

  public isActive(): boolean {
    return this.status === ReservationStatus.ACTIVE
  }

  public isCancelled(): boolean {
    return this.status === ReservationStatus.CANCELLED
  }

  public canBeModified(): boolean {
    if (!this.isActive()) {
      return false
    }

    const now = new Date()
    const today = new Date()
    today.setUTCHours(0, 0, 0, 0)

    const reservationDate = new Date(this.reservationDate)
    reservationDate.setUTCHours(0, 0, 0, 0)

    // If reservation is for a future date, it can be modified
    if (reservationDate > today) {
      return true
    }

    // If reservation is for today, check the 8:30 AM cutoff
    if (reservationDate.getTime() === today.getTime()) {
      const cutoffTime = new Date()
      cutoffTime.setUTCHours(8, 30, 0, 0)
      return now < cutoffTime
    }

    // If reservation is for a past date, it cannot be modified
    return false
  }
}
