import { Device, DeviceRepository, DeviceStatus } from "./domain"
import { AppError } from "@/app/shared"
import { CreateDeviceDTO } from "./dtos"

// Temporary interface for WebSocketService until it's implemented in task 3.2
interface WebSocketService {
  emitDeviceCreated(device: Device): void
  emitDeviceStatusChanged(device: Device): void
}

export class DeviceService {
  constructor(
    private deviceRepository: DeviceRepository,
    private websocketService?: WebSocketService
  ) {}

  async create(data: CreateDeviceDTO): Promise<Device> {
    // Validate MAC uniqueness
    const existingDevice = await this.deviceRepository.findByMac(data.mac)

    if (existingDevice) {
      throw new AppError("Device with this MAC address already exists", 409)
    }

    const device = new Device(
      "", // ID will be generated by the repository
      data.name,
      data.mac,
      DeviceStatus.ATIVO, // Default status
      new Date()
    )

    const createdDevice = await this.deviceRepository.create(device)

    // Emit WebSocket event if service is available
    if (this.websocketService) {
      this.websocketService.emitDeviceCreated(createdDevice)
    }

    return createdDevice
  }

  async findAll(): Promise<Device[]> {
    return await this.deviceRepository.findAll()
  }

  async findById(id: string): Promise<Device> {
    const device = await this.deviceRepository.findById(id)

    if (!device) {
      throw new AppError("Device not found", 404)
    }

    return device
  }

  async toggleStatus(id: string): Promise<Device> {
    const device = await this.deviceRepository.findById(id)

    if (!device) {
      throw new AppError("Device not found", 404)
    }

    device.toggleStatus()

    const updatedDevice = await this.deviceRepository.update(id, device)

    // Emit WebSocket event if service is available
    if (this.websocketService) {
      this.websocketService.emitDeviceStatusChanged(updatedDevice)
    }

    return updatedDevice
  }
}
